# name of the deployment AND the app-id for dapr if enabled
name: test-ms-name
image: test-image
tag: test-tag-1
# if host is specifed an ingress will be created
host: test.tester.com
# array of env variables to apss, either in deployment or as a secret
env:
  secret:
    ConnectionStrings__DatabaseConnection: mysecretconnectionstringhere
  normal:
    AppSettings__SendEmailAlerts: false

# optional parameters

#imagePullSecret: docker-wecma

# if ingress is created dont make ssl certificate
#disableSsl: false

# dapr will be enabled by default
#enableDapr: false

# dapr debugging will be diabled by default
#enableDaprDebugLog: false