# name of the deployment AND the app-id for dapr if enabled
name: test-ms-name
image: test-image
tag: test-tag-1
# if host is specifed an ingress will be created
host: test.tester.com
# optional parameters

#pullEnvfromSecret: true
#imagePullSecret: docker-wecma

# if ingress is created dont make ssl certificate
#disableSsl: false
