apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: Always
        name: {{ .Values.name }}
        stdin: true
        tty: true
        {{- if .Values.env }}
        env:
        {{- if .Values.env.secret }}
        {{- $projname := .Values.name -}}
        {{- range $key, $val := .Values.env.secret }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $projname }}
              key: {{ $key }}
        {{- end }}
        {{- end }}
        {{- if .Values.env.normal }}
        {{- range $key, $val := .Values.env.normal }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end}}
        {{- end }}
        {{- end }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      restartPolicy: Always